import { Routes } from '@angular/router';
import { AboutComponent } from './about/about.component';
import { AccordionDemoComponent } from './accordion-demo/accordion-demo.component';
import { AlertDemoComponent } from './alert-demo/alert-demo.component';
import { AutocompleteDemoComponent } from './autocomplete-demo/autocomplete-demo.component';
import { HomeComponent } from './home/home.component';
import { BadgeDemoComponent } from './badge-demo/badge-demo.component';
import { ButtonDemoComponent } from './button-demo/button-demo.component';
import { CheckboxDemoComponent } from './checkbox-demo/checkbox-demo.component';
import { DatePickerDemoComponent } from './date-picker-demo/date-picker-demo.component';
import { DateRangePickerDemoComponent } from './date-range-picker-demo/date-range-picker-demo.component';
import { InputDemoComponent } from './input-demo/input-demo.component';
import { LayoutDemoComponent } from './layout-demo/layout-demo.component';
import { ModalDemoComponent } from './modal-demo/modal-demo.component';
import { PaginationDemoComponent } from './pagination-demo/pagination-demo.component';
import { ProgressDemoComponent } from './progress-demo/progress-demo.component';
import { RadioDemoComponent } from './radio-demo/radio-demo.component';
import { SelectDemoComponent } from './select-demo/select-demo.component';
import { SkeletonDemoComponent } from './skeleton-demo/skeleton-demo.component';
import { SliderDemoComponent } from './slider-demo/slider-demo.component';
import { SpinnerDemoComponent } from './spinner-demo/spinner-demo.component';
import { TabDemoComponent } from './tab-demo/tab-demo.component';
import { TableDemoComponent } from './table-demo/table-demo.component';
import { TextareaDemoComponent } from './textarea-demo/textarea-demo.component';
import { ToastDemoComponent } from './toast-demo/toast-demo.component';
import { ToggleDemoComponent } from './toggle-demo/toggle-demo.component';
import { TooltipDemoComponent } from './tooltip-demo/tooltip-demo.component';
import { TextHighlightDemoComponent } from './text-highlight-demo/text-highlight-demo.component';
import { VirtualScrollDemoComponent } from './virtual-scroll-demo/virtual-scroll-demo.component';
import { VideoPlayerDemoComponent } from './video-player-demo/video-player-demo.component';

export const routes: Routes = [
    { path: '', component: HomeComponent, pathMatch: 'full' },
    { path: 'accordion', component: AccordionDemoComponent },
    { path: 'alert', component: AlertDemoComponent },
    { path: 'autocomplete', component: AutocompleteDemoComponent },
    { path: 'badge', component: BadgeDemoComponent },
    { path: 'button', component: ButtonDemoComponent },
    { path: 'checkbox', component: CheckboxDemoComponent },
    { path: 'date-picker', component: DatePickerDemoComponent },
    { path: 'date-range-picker', component: DateRangePickerDemoComponent },
    { path: 'input', component: InputDemoComponent },
    { path: 'layout', component: LayoutDemoComponent },
    { path: 'modal', component: ModalDemoComponent },
    { path: 'pagination', component: PaginationDemoComponent },
    { path: 'progress', component: ProgressDemoComponent },
    { path: 'radio', component: RadioDemoComponent },
    { path: 'select', component: SelectDemoComponent },
    { path: 'skeleton', component: SkeletonDemoComponent },
    { path: 'slider', component: SliderDemoComponent },
    { path: 'spinner', component: SpinnerDemoComponent },
    { path: 'tab', component: TabDemoComponent },
    { path: 'table', component: TableDemoComponent },
    { path: 'text-highlight', component: TextHighlightDemoComponent },
    { path: 'textarea', component: TextareaDemoComponent },
    { path: 'toast', component: ToastDemoComponent },
    { path: 'toggle', component: ToggleDemoComponent },
    { path: 'tooltip', component: TooltipDemoComponent },
    { path: 'virtual-scroll', component: VirtualScrollDemoComponent },
    { path: 'video-player', component: VideoPlayerDemoComponent },
    { path: 'about', component: AboutComponent },
];
